# TypeError: 'list' object is not callable



**Version: Python 3.8.3**



파이썬에서 일어나는 에러 중

TypeError: "\____" object is not callable

라는 에러 문구가 출력 된다.



![image-20201016092010742](https://i.loli.net/2020/10/16/9WZzsvjkiVmuQwb.png)

여기서 ____에는 str, list등 여러가지 에러가 난다.





### 원인

**위에서 선언한 변수를 함수처럼 사용하려고 할 때 발생.**

<img src="https://i.loli.net/2020/10/16/W92njDoLdI74iKx.png" alt="image-20201016092230190" style="margin-left:0px;" />



문제가 되는 부분은 map이라는 변수를 선언하고,

밑에서 파이썬이 내장된 map함수를 이용할 때 발생하는 문제이다.



여기서 ___의 내용은 내가 선언한 변수의 타입이 나오게 된다.

변수를 함수처럼 사용하려고 해서 **is not callable**이 나오게 된 것.



### 결론

함수 명으로 자주 쓰이는 단어나 파이썬의 내장 함수의 이름으로는 변수의 이름을 쓰지 않는 것이 좋다. 

위 같은 에러가 나오면 같은 이름의 변수가 선언된 건 아닌지 확인해 보길 바란다. 

